[project]
name = "agent-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "colorama>=0.4.6",
    "prompty[azure]==1.0.0b3",
]

[dependency-groups]
dev = [
    "types-colorama>=0.4.15.20250801",
]
